### PR TITLE
Change over shiny app framework to bslib?

### LINKED ISSUE #49: Replace shinydashboard with bslib
shinydashboard is stuck in bootstrap 3 and we're on bootstrap 5+ now. 

if it's relatively painless would be good to do

### PR DESCRIPTION
**Pull request by sckott**
fixes #49 

This is currently a work in progress, but I'd still like to get initial reactions from folks BECAUSE if we don't want to go down this route for whatever reasons, then it doesn't make sense to keep working on this. There's a lot of work in progress on this branch so please just focus on how it looks visually and not so much on commented out code, etc.

A big question hanging over this too is how soon are we moving away from Shiny. If we're not going to start work on a non shiny version for 6 months or a year, then probably makes sense to leverage the much improved bslib, but if we're planning to start work on non shiny version sooner then maybe this isn't worth it since the required time is non-trivial to get this working

also pinging @codebeaker 

## to run it

You can't see this deployed because we only have that setup for main and dev, but you can run it locally with a new make command, see https://github.com/FredHutch/shiny-cromwell/tree/dev?tab=readme-ov-file#run-a-feature-branch-locally 

After getting login creds from Dan, run `make branch=bslib run_branch` from this repo locally and it should pull up this branch on localhost 3838

### CODE REVIEW

**Comment by tefirman** [comment]
Nice, looks clean for sure! You mentioned bslib is much improved in this version, is it just cleaner visually or is it easier to work with from a developer's standpoint?

**Comment by sckott** [comment]
Thanks for looking @tefirman 

> You mentioned bslib is much improved in this version, is it just cleaner visually or is it easier to work with from a developer's standpoint?

To be clear, we are not using `bslib` at all in the old codebase. The equivalent to `bslib` is `shinyDashboard` and associated pkgs. 

It's cleaner and more modern looking and I think easier to work with too. It's nice to be able to work with modern bootstrap rather than being stuck on pretty old bootstrap version. 

There's a possibility that features we have in the old shiny code may not be exactly portable to how `bslib` behaves, but I imagine we can work around those things.

**Comment by tefirman** [comment]
## Update
- It is becoming more and more evident that these GUI updates are necessary for the overarching usability of PROOF. They provide a more professional-looking/intuitive interface and reduce the amount of scrolling necessary to drive the tool.
- While we’re not quite ready to merge these changes into `main`, @codebeaker is performing some user studies to identify what parts of these updates are helpful and what parts can still be improved. Building the interface locally works, but results in a slower interface and less productive user study experience.
- We would like to merge the interface updates implemented thus far into the `dev` branch. This will allow us to use the dev instance of PROOF ([proof-dev.fredhutch.org](http://proof-dev.fredhutch.org/)) for further user studies and testing of the new interface. These updates have been built locally by multiple users and all previous functionalities work as expected.
- The production server will remain as-is until the v1.2 release and we can always revert the dev server to the previous interface if issues arise with these updates. If you would like to voice any concerns about this approach, please comment below or reach out to @seankross and @tefirman.

**Review by tefirman — APPROVED** [review]
See comment above for approval rationale.

**Pull request merged**
