### PR TITLE
Use cookies to store user login data

### LINKED ISSUE #118: Persist User Login with Cookies
Every time the PROOF page is refreshed, it automatically logs out the user and they have to log in again. Not critical, but definitely annoying, wondering if we can persist the login via cookies or something. Discussed this with Scott previously, but personally not 100% sure exactly how to do this.

### PR DESCRIPTION
**Pull request by sckott**
fix #118 

This adds cookies for just username and password, so that those data are not lost when the app gets refreshed, and/or when the user opens up the app in another (non-private) tab in the same browser. 

This approach persists the data in a Mariadb database, which is more database than we need, but when it doesn't cost extra it seems fine. And we may want to persist other data to the database in the future anyway

This will be a nice quality of life improvement for working on the app code as well because the session login won't be lost when the app refreshes on each code change 😄 

also @sitapriyamoorthi review please and thx

## to run it

You can't see this deployed because we only have that setup for main and dev, but you can run it locally with a new make command, see https://github.com/FredHutch/shiny-cromwell/tree/dev?tab=readme-ov-file#run-a-feature-branch-locally 

After getting login creds from Dan, run `make branch=cookie-cutter run_branch` from this repo locally and it should pull up this branch on http://0.0.0.0:3838

### CODE REVIEW

**Review by dtenenba — COMMENTED** [review]
Hi Scott,

This looks good! 

How would you feel about increasing the timeout from 1 day to something larger? I don't think people should have to log in every day or even every week.

Also, from a quick glance at the code it does not look like passwords are stored in the database or in the cookie; can you confirm that? 

Thanks for this!

**Comment by sckott** [comment]
Sure, maybe change the expiration to 2 weeks?

We do store the username in the cookie, and just the username

In the database, we store the username and proof token, see the function `user_to_db`

**Comment by sckott** [comment]
> It appears to be your server based on the paths and slurm account

That's a bummer. I'll see about it

**Comment by sckott** [comment]
@dtenenba is there a time tomorrow you can hop on a quick call to test this out with me so I can see another user using this version of the app? For me tomorrow, before 10 or after 1

**Comment by sckott** [comment]
Issues dealt with:

- [x] user A was ending up with data from user B. problem was a block of code was grabbing a cookie, the cookie was empty, and then we queried the `users` db table with an empty string and just get back everything from the table - and if there's anything there, it will be that user - added extra checks to make sure we're not doing that
- [x] change `dbSendQuery` to `dbGetQuery` so that delete data works - `dbSendQuery` "worked" but didn't actually do the thing

Issues remaining:

- [ ] Multiple records per user are in the `users` table in the database. ideally drop any entries for any user before inserting so there's only 1 per user
- [ ] Make sure username is not displayed to left of the login button upon log out - should have been fixed in 6910766 but check to make sure

**Review by tefirman — APPROVED** [review]
Just tested the cookie functionality with @dtenenba and @sckott to ensure the issue from last week no longer occurs. Worked great! Server identifies the correct user info upon login and the user remains logged in even if they navigate away.

We should open this up to other DaSL users for an even larger sample size of testing, which will be easier to do once merged into `dev` but confident enough to merge to `main` upon the next version release.

**Comment by sitapriyamoorthi** [comment]
Testing on this URL: https://proof-dev.fredhutch.org/ doesnt seem to be working for me

**Comment by dtenenba** [comment]
Can you clarify what is not working?

I went to https://proof-dev.fredhutch.org/ and logged in, and then reloaded the page, and it showed that I was still logged in. That did not work before.

**Comment by sitapriyamoorthi** [comment]
Happy to clarify. 
I wen to the same link as you have indicated. Logged in. Refreshed the page. And it logs me out.

**Comment by dtenenba** [comment]
Thanks. It might be worth trying another browser and/or clearing cache and deleting any cookies that the shiny app might have given you.

**Comment by sckott** [comment]
I'm going to hop on a call with Sita soon here and discuss ...

**Comment by sitapriyamoorthi** [comment]
Okay @sckott and I tried a couple of things:
1. Tried different browsers: issue persists
2. Tried docker version of app: app start gave errors
3. Tried local instal through R: after resolving package install issues gave errors for access `Warning: Error in : Failed to connect: Access denied for user 'smoorthi'@'localhost' (using password: NO) `
4. Tried switichin WiFi : Issue persists

**Comment by sitapriyamoorthi** [comment]
Life is funny... now it works (post magic words + Dan + Scott magic)

**Pull request merged**
