### PR TITLE
shiny-cromwell v1.2.0 Updates

### LINKED ISSUE #49: Replace shinydashboard with bslib
shinydashboard is stuck in bootstrap 3 and we're on bootstrap 5+ now. 

if it's relatively painless would be good to do

### LINKED ISSUE #112: Allow for partial match in workflow name search
- In the "Track Jobs" tab of PROOF, we allow for the search of workflows by name using the "Filter for workflows with name:" text box. However, you need to match the workflow name **exactly** for it to work.
- It would be helpful to allow for some sort of wildcard functionality, where it displays all workflows with at least a partial match of what was entered.
- To start, we could even just do a "startswith" functionality, e.g. a search of "hello" would populate all workflows with names like "helloWorld" and "helloFredHutch", or maybe a "contains" functionality, e.g. a search of "bar" would find both "foobar" and "barometric".
- This would be particularly relevant if we add a search for workflow labels as well.

### LINKED ISSUE #114: app says "Your server is not up" when it is
I was trying to do a one-person stress test and I had the PROOF app open in 3 browser tabs. I had a proof server running and I was logged into each tab and I had uploaded a simple WDL to each in the Submit Jobs tab. 
I clicked Submit Job in the first tab and it worked fine, and then clicked the same button in the other 2 tabs right away. In both tabs I got the message `Error: Your server is not up!` and this appeared in the app logs:

```
Error in : Your server is not up!
<Anonymous>
stop
stop_safe
stop_safe_loggedin_serverup
renderPrint [/srv/shiny-server/server.R#409]
func
renderFunc
output$submissionResult
runApp
```

But then if I go to the PROOF Server tab, in all 3 tabs, it says my server is RUNNING.

I wonder if the code is consulting a local or session variable to determine whether the server is running (when submitting a workflow), and since the server was started in another session/tab, it doesn't realize there is a running server. Maybe instead it could consult the PROOF API.
On the other hand, this is a bit of a contrived situation and I am not sure how important it is to track this down.

### LINKED ISSUE #119: Server up but, validate tab says its not
Started a PROOF server. Got the email saying PROOF server is ready. Tried to validate a workflow but validate tab says my server is not ready. Logging out and re-logging back in solved the issue. 

Screenshot 2024-08-07 at 1 16 27 PM
Screenshot 2024-08-07 at 1 16 35 PM
Screenshot 2024-08-07 at 1 16 46 PM
Screenshot 2024-08-07 at 1 21 46 PM

### LINKED ISSUE #132: DIY Cromwell button reappearing
DIY Cromwell button is being shown when using cookies after a page refresh - not entirely sure why yet

via #130

### LINKED ISSUE #144: Add bits and bobs back in before merging bslib to main
- [x] google analytics, variable `google_analytics` in `app/ui_components.R`
- [x] enter to click js script, variable `enter_to_click` in `app/ui_components.R`
- [x] tooltip styling, variable `tooltip_style` in `app/ui_components.R`
- [x] add back `table_footer` where needed, not sure it's been reapplied in new setup

These were taken care of already:

- ~~Help dropdown was removed as I couldn't fix styling in bslib-land. Figure out if we should put back and where~~
- ~~Source code dropdown was removed as I couldn't fix styling in bslib-land. Figure out if we should put back and where~~

### LINKED ISSUE #145: Error messages when user is not logged in
df5c3920-be29-4f16-852c-11158bcfcfe2

Dan suggested changing the message to say to log in, BUT I think I'd prefer no error message there or other places when not logged in. 

Ideally we just implement a separate login page and then this class of problem goes away, but until then I'd prefer just not to show any message in these cases when not logged in

### LINKED ISSUE #146: Clean out old code
There's a bunch of old code from the previous version before bslib that's not used anymore  - clean it out

### LINKED ISSUE #154: update header with Fred Hutch branding
Fred-Hutch-Logo-Primary-Reverse
We should update the header to:
1) Have the Fred Hutch logo (so it looks like [reverse primary white on black](https://brand.fredhutch.org/d/KPkLjsrU6mM4/brand-guidelines#/visual-elements/logo))
2) Have a black background
3) Have the 'Welcome' screen content be linked from 'PROOF' and get rid of the word 'Welcome'
4) Change 'Resources' to 'Help' and move it to the end
[Figma ](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=477-26&t=0zdNr3XYbr0JbH2C-1)

### LINKED ISSUE #155: update text on the landing page
1) Change 'This' to "PROOF (Production Onramp for Optimization and Feasibility)"
2) Update 'Resources page' to 'Help'/'Get help'/whatever variation we go with

[figma](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=477-26&t=0zdNr3XYbr0JbH2C-1)

### LINKED ISSUE #156: Update Resources/Help content
1) Change top 'resources' header to "Getting Help with PROOF and WDL at Fred Hutch"
2) Change bottom 'resources' header to "Some Resources for Using Cromwell"
3) Add any other help content like how to email us, link to file an issue on github, etc.
[Figma](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=481-66&t=UeLdktFOgvSwMEnp-1)

### LINKED ISSUE #157: Updates to server page
1) Add a sentence that stopping your PROOF server will not stop your job
2) Add some kind of loading indicator for when some page content has loaded but not server info
3) make the styles for "Note" consistent: bold with colon works well 
[Figma](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=485-113&t=UeLdktFOgvSwMEnp-1)

### LINKED ISSUE #158: Submit page changes
1) Disable submit button when nothing uploaded or after something submitted until form is reset or something else uploaded
2) Make submit button green (same as 'start server') when enabled
3) give button a loading state when submission in progress (spinny disk, faded out)
4) Move workflow id and status info (when it appears) to underneath submit button, above reset form button
[Figma](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=486-116&t=UeLdktFOgvSwMEnp-1)

### LINKED ISSUE #159: Updates to Track Workflows page
1) Add a loading indicator for when page content is loading
2) Have the title bar of a card show workflowname (label1, label2) instead of workflow id
3) move workflow Id to bottom left of card
4) have loading state for 'workflow details' button for when you have clicked it and it is still loading
[Figma](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=486-269&t=UeLdktFOgvSwMEnp-1)

### LINKED ISSUE #160: Workflow details page updates
1) move 'troubleshoot' to a tab here
2) have a loading indicator for when content is loading
3) have a sentence for when there is truly no content, e.g. for workflow options if there is no content there can be a sentence saying what would be there and that it's empty for this workflow
4) change title bar to 'WorkflowName (label1, label2)' instead of what it currently is which is something like 'workflow details for [workflowID]'
5) put workflow ID in top right of title bar where labels currently are
6) note in the new version there are no icons for the labels

[figma](https://www.figma.com/design/TB7G3FakSSZOMNW1GALi1x/proof-bs?node-id=493-424&t=0zdNr3XYbr0JbH2C-1)

### LINKED ISSUE #164: Clear workflow details outputs before the app switches to the details tab
clear any outputs on workflow details tabs before the app switches to the details tabs so that data for a previous workflow doesn't get confused with the new one the user is looking at

right now they are not cleared and it is no bueno

### LINKED ISSUE #165: Dev UI: No way to update the Job List
from https://github.com/getwilds/proof/issues/19 (can not transfer issues btw orgs)

from @sitapriyamoorthi

> In the previous version of PROOF I was able to see what jobs were running by task in track workflows.
When I would refresh this it would get updated.
Now there is no option for me to get real-time information in the Job list page of workflow description.
Perhaps an update button of some sort is needed?

### LINKED ISSUE #173: Date sorting doesn't actually work
It's not wired up, ha 😢

### LINKED ISSUE #192: Implement tickle server idea from main branch
https://github.com/FredHutch/shiny-cromwell/pull/191 

In that PR we fixed (I think) in app server change issues that are still happening in the dev branch bslib side of things. 

Merging to main may not work to retain this change, so implement before merge probably

### PR DESCRIPTION
**Pull request by tefirman**
## Description
- Changing over shiny app framework to bslib (@sckott and @codebeaker)
    - Cleaner and more modern-looking interface, improved usability for researchers ([#162](https://github.com/FredHutch/shiny-cromwell/pull/162), [#169](https://github.com/FredHutch/shiny-cromwell/pull/169), [#174](https://github.com/FredHutch/shiny-cromwell/pull/174), [#193](https://github.com/FredHutch/shiny-cromwell/pull/193))
    - Updated version of bootstrap, easier to use from a programming standpoint ([#129](https://github.com/FredHutch/shiny-cromwell/pull/129))
    - Improved metadata reactions ([#170](https://github.com/FredHutch/shiny-cromwell/pull/170), [#171](https://github.com/FredHutch/shiny-cromwell/pull/171), [#191](https://github.com/FredHutch/shiny-cromwell/pull/191))
- Updating base image of R in Dockerfile (@dtenenba in [#143](https://github.com/FredHutch/shiny-cromwell/pull/143))
- Removing unnecessary code (@sckott in [#149](https://github.com/FredHutch/shiny-cromwell/pull/149))

## Related Issues
- Fixes #49 
- Fixes #132 
- Fixes #119 
- Fixes #145 
- Fixes #114 
- Fixes https://github.com/getwilds/proof/issues/9
- Fixes #112 
- Fixes #144
- Fixes #146
- Fixes #154
- Fixes #155
- Fixes #156
- Fixes #157
- Fixes #158
- Fixes #159 
- Fixes #160
- Fixes #164
- Fixes #165
- Fixes #173
- Fixes #192

## Testing & Examples
- See links to individual PR's listed above

### CODE REVIEW

**Comment by sckott** [comment]
@tefirman i'm about to ask for feedback on https://github.com/FredHutch/shiny-cromwell/pull/162 tomorrow morning - include that here as well?

**Comment by tefirman** [comment]
@sckott -- 100%, just added #162 and its related issues above. Let me know when you're ready for feedback!

**Comment by sckott** [comment]
thanks, that PR is ready to look at now

**Comment by sckott** [comment]
@tefirman bits and bobs in PR https://github.com/FredHutch/shiny-cromwell/pull/169

**Review by sckott — APPROVED** [review]

**Pull request merged**
