### PR TITLE
add capability to convert wdl to mermaid

### PR DESCRIPTION
**Pull request by dtenenba**
I added a function to the end of utils.R called wdl2mermaid. It takes a filename of a wdl file and returns a character vector of length 1 containing a mermaid diagram. 

This also includes the infrastructure for installing https://github.com/chanzuckerberg/miniwdl-viz 

We still need functionality to display the mermaid diagram. 

There was a suggestion about adding this to rcromwell instead but I think it might be better to have it here because this is dockerized so it's easy to install the dependencies. I don't want R users to have to deal with an R package installing python stuff.

### CODE REVIEW

**Comment by sckott** [comment]
Thanks Dan. Your addition works good. I played around with then visualizing in the app and no success yet. So far:

- R pkg https://rich-iannone.github.io/DiagrammeR/ has what I thought would work, but it seems like it's stuck on a vendored old version of mermaid, and it doesn't seem to parse the dot notation from the wdl's. 
- Tried just importing mermaid js and haven't figured that out yet. They suggest using a `<pre>` tag which then renders an svg in that place, but that's not a straightforward translation into shiny land. There's probably a way to use the mermaid js api to do the svg creation manually, but haven't tried that yet

**Comment by dtenenba** [comment]
If you want to convert the mermaid to svg, then that can also be done in python. I do it using the `dot` command line program. But there are more interactive ways. 

I asked a "friend" how to do this and after several tries, they got it to work.

https://chatgpt.com/share/b8432d0f-a894-40b0-a450-039d2f27836b

**Comment by sckott** [comment]
Nice. Maybe I should start playing with ai stuff. 

I hadn't seen the `dot` tool, just installed that.

**Comment by sckott** [comment]
@dtenenba So I don't know of a way to get the submitted WDL file for a workflow. Do you? 

It is true that we'd have the WDL files of submitted workflows during a session, but clearly users would want to view WDL's with this for older workflows submitted in previous sessions. 

Maybe we could add an endpoint to the PROOF API to get files for a workflow ID? Or some other way?

**Comment by sckott** [comment]
actually, looks like we can get the entire workflow text from the route `/api/workflows/v1/{workflow_id}/metadata` from the field `submittedFiles$workflow`

**Comment by tefirman** [comment]
@dtenenba -- I tried testing this out locally using `make run_docker` and unfortunately I'm only seeing a blank screen on the "WDL" tab (see screenshot below). Do I need to select a workflow on a separate tab for this to work? Just wondering if I'm using this wrong or if my Docker build failed somehow..
image

**Comment by dtenenba** [comment]
@tefirman I am not sure if @sckott has added a UI for this yet. What I did was just the plumbing, without the UI. You can check it's working as described [here](https://fhdata.slack.com/archives/C068PB2EG01/p1723840602396059?thread_ts=1723832095.601419&cid=C068PB2EG01).

**Comment by dtenenba** [comment]
It looks like there [is a ui](https://github.com/FredHutch/shiny-cromwell/pull/125/files#diff-226b88640b40efe023421eec38121bb662fdad911c727c4768a3e14525ee8f6aR584).

**Comment by sckott** [comment]
Good idea @tefirman to add a button to go back to track jobs tab. I'll do that

**Comment by sckott** [comment]
Okay try again @tefirman

**Comment by sckott** [comment]
Some notes on the WDL tab. 

- The addition of a new column to the table on tracking page with a search icon make the table uglier but I think we'll fix this when we move to non shiny (though I guess we could do here, but seems like wasted effort if we're moving away from shiny) and move from a table to more of a list of cards setup where we can have filtering on like bootstrap cards that contain links and buttons and such and it won't be so unwieldy. 
- Maybe we just get this into dev and start getting feedback from more folks though instead of iterating here? 

-----

- It'd be nice to have some user controls like you get in a GitHub rendered page, but maybe this barebones solution is fine?
- It'd be nice if it could fit to the screen, so if it's a small diagram it doesn't just take up a tiny bit of real estate on the page
- The yellow background is kinda ugly, need to look into style tweaks

Screenshot 2024-08-26 at 1 14 20 PM

- This is what an error looks like - probably want to handle that somehow

Screenshot 2024-08-26 at 1 15 33 PM

- Large ones go off the yellow background and onto the rest of the page, kinda ugly, but I guess functional?

Screenshot 2024-08-26 at 1 16 40 PM

**Comment by tefirman** [comment]
> * Maybe we just get this into dev and start getting feedback from more folks though instead of iterating here?

Agreed, let's merge both this and the input json visualization PR's into dev and we can iterate from there. Both tools do what we want them to do, we just need a bit of testing/refinement, which is much easier to do in dev. Might be cool to combine this into one tab, e.g. "Job Details", but again, we can iterate on this to figure out what works best. 

Thanks @dtenenba and @sckott for your work on this!!

**Comment by sckott** [comment]
Good idea to try for one Job Details tab. I'll see how that goes

**Pull request merged**
