### PR TITLE
Test packages are installed

### PR DESCRIPTION
**Pull request by dtenenba**
Adds a unit test that checks to see if any packages that are referenced in .R source files (via `library()`, `require()`, `requireNamespace()`, `::` or `:::`) are not installed. 
Runs the test during CI/CD build. 

I guess this could replace the check in the Dockerfile (using `check.R`). Which is good because you have to remember to add files to the Dockerfile in 2 places. Now the unit test will tell you what is missing.

Outside of CI/CD, you can run the tests like this:

```R
R -q -e 'testthat::test_dir("app/tests")'
```

I encourage you to squash all the fiddly little commits if you merge this. 😀

### CODE REVIEW

**Review by sckott — APPROVED** [review]
LGTM. I think we should remove the check.R bits in the Dockerfile and just use this test instead - removes the requirement to list each pkg in two places in that file.

**Comment by dtenenba** [comment]
Agreed, added one more commit to take that out.

**Comment by sckott** [comment]
looks like the build failed from the CI above, but on the build logs viewer it looks like it passed?

**Comment by dtenenba** [comment]
Yeah, that was a spurious failure. It has built successfully since then but github is not picking up on that for some reason.

**Comment by sckott** [comment]
woops, i forgot to squash, sorry about that. hope thats okay

**Comment by dtenenba** [comment]
No worries!

**Pull request merged**
